In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import io
from sklearn.model_selection import train_test_split
import math
import sys
from scipy.special import expit

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
data_ = pd.read_csv('/content/gdrive/My Drive/CS5691/assignment-2/datasets/Regression_dataset.csv')

In [ ]:
data_train, data_test = train_test_split(data_, test_size = 0.25, random_state = 3)
data_train = data_train.values
data_test = data_test.values

In [ ]:
x_train = data_train[:, 0:13]
y_train = data_train[:,13]

x_test = data_test[:,0:13]
y_test = data_test[:,13]

In [ ]:
m = x_train.shape[0]

In [ ]:
def poly_kernel(input_matrix, p):
    if p == 1:
        return input_matrix
    elif p == 2:
        a = input_matrix
        b = np.power(input_matrix[:, 0:13], 2)
        out = np.hstack((a, b))
        return out
    elif p == 3:
        a = input_matrix
        b = np.power(input_matrix[:, 0:13], 2)
        c = np.power(input_matrix[:, 0:13], 3)
        out = np.hstack((a, b, c))
        return out

In [ ]:
class RidgeRegression():
  def __init__(self, alpha=1.0, lamba = 0.001):
      self.alpha = alpha
      self.lamba = lamba

  def fit(self, X, y):
      X_with_intercept = np.c_[np.ones((X.shape[0], 1)), X]
      self.X_intercept = X_with_intercept
      
      dimension = X_with_intercept.shape[1]
      A = np.identity(dimension)
      A[0, 0] = 0
      lamba = self.lamba*A
      thetas = np.linalg.inv(X_with_intercept.T.dot(X_with_intercept) + lamba).dot(X_with_intercept.T).dot(y)
      self.thetas = thetas
      return self

  def predict(self, X):
      thetas = self.thetas
      final_X = np.c_[np.ones((X.shape[0], 1)), X]
      self.predictions = final_X.dot(thetas)
      return self.predictions

In [ ]:
lin_mod = RidgeRegression(alpha = 0.01, lamba = 10)
lin_mod.fit(x_train,y_train)
lin_mod.predict(x_train[0:10])

array([32.22089168, 13.78000953, 23.31417467, 26.64289528, 37.33741373,
       18.61437962, 30.10019902, 22.09674603, 16.36680294, 24.67128976])

In [ ]:
y_train_lin = lin_mod.predict(x_train)
y_test_lin = lin_mod.predict(x_test)

In [ ]:
new_x_train = poly_kernel(x_train,2)
poly_mod = RidgeRegression(alpha = 0.01, lamba = 10)
poly_mod.fit(new_x_train,y_train)
poly_mod.predict(new_x_train[0:10])

array([34.7555481 , 11.76671226, 24.27636928, 27.54181005, 42.8444749 ,
       16.49181037, 32.00892585, 19.05898698, 14.48233498, 23.44323903])

In [ ]:
new_x_test = poly_kernel(x_test,2)
y_train_poly = poly_mod.predict(new_x_train)
y_test_poly = poly_mod.predict(new_x_test)

In [ ]:
y_train[0:10]

array([35.4, 13.5, 20.6, 24.7, 21.9, 17.1, 23.6, 21.1, 15.6, 18.5])

In [ ]:
def mse_metric(actual, predicted):
	sum_error = 0.0
	for i in range(len(actual)):
		prediction_error = predicted[i] - actual[i]
		sum_error += (prediction_error ** 2)
	mean_error = sum_error / float(len(actual))
	return mean_error

In [ ]:
mse_lin_train = mse_metric(y_train, y_train_lin)
mse_poly_train = mse_metric(y_train, y_train_poly)
mse_lin_test = mse_metric(y_test, y_test_lin)
mse_poly_test = mse_metric(y_test, y_test_poly)
print(mse_lin_train, mse_poly_train)
print(mse_lin_test, mse_poly_test)

23.953292401348488 17.59596069912533
20.235277110067646 13.928451655185148
